### ISSUE TITLE
3/16/2020: Code blocks that are markdown image urls are mangled

### ISSUE THREAD

**Issue by TylerLeonhardt** [fastai/fastpages#215] opened 2020-03-17 05:42 UTC
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

Take a look at this notebook and scroll down to the NOTE.
https://tylerleonhardt.github.io/blog/2020/03/16/Word-Clouds.html

I'm using a magic command `#!markdown` to render markdown instead of a normal code block so I can show the markdown code behind it.

Unfortunately, for some reason fastpages mangles the path of my svg in the code sample:

```
![.NET Interactive codebase word cloud](/blog/images/copied_from_nb/dotnet-interactive.svg)
```
instead of
```
![.NET Interactive codebase word cloud](dotnet-interactive.svg)
```

which is what it is in source:
https://github.com/TylerLeonhardt/blog/blob/56e0f224d03866fd5118131ab41bcb8effb81453/_notebooks/2020-03-16-Word-Clouds.ipynb#L110

## Expected Behavior

My url isn't touched.

```
![.NET Interactive codebase word cloud](dotnet-interactive.svg)
```

## Actual Behavior

My url is mangled.

```
![.NET Interactive codebase word cloud](/blog/images/copied_from_nb/dotnet-interactive.svg)
```

## Proposed solution

Don't expand image tags in Code blocks?

**Comment by TylerLeonhardt** [comment] 2020-03-17 05:43
I didn't try it, but I don't know if the _output_ was touched at all... as in I don't think the img Urls were touched.

**Comment by hamelsmu** [comment] 2020-03-17 12:49
This is expected behavior.  Fastpages copies your image from your local folder to a folder where it can be served on your site and thus changes the path

Closing issue because included url above leads to a 404 so I cannot see the problem.  Feel free to ask more questions!  I suggest posting in forums.fast.ai for more visibility on this one as I don’t think it’s a bug and could also be confusion about how nbdev works

**Closed by hamelsmu** 2020-03-17 12:49 UTC
Labels: bug

**Comment by TylerLeonhardt** [comment] 2020-03-17 14:47
Ah sorry, I forgot tags change a blog post's URL. Here's the working URL:
https://tylerleonhardt.github.io/blog/jupyter/powershell/pswordcloud/2020/03/16/Word-Clouds.html

**Comment by hamelsmu** [comment] 2020-03-17 15:01
Ok I see.  This is a feature, not a bug.  Your path changes because fastpages moves the image for you from you local folder!   The way Jekyll works is that images in `_notebooks` will not be visilbe to the build system.  This is so you don't have to move the image yourself.  Otherwhise, you would have to do this manually. 

https://www.fast.ai/2020/01/16/fast_template/

![image](https://user-images.githubusercontent.com/1483922/76869290-56f1fe80-6825-11ea-8b19-18c4b847602b.png)

Thanks

**Comment by TylerLeonhardt** [comment] 2020-03-17 15:08
But why does fastpages modify URLs inside of a _Code_ cell and not strictly only _Markdown_ cells?

I would think that Code cells shouldn't ever be messed with since the reader actually _sees_ the Code cell.

And a side point to that is... If Code cells are touched, why is the _Output of a Code cell_ not touched?

**Comment by hamelsmu** [comment] 2020-03-17 15:20
Oh ... I misinterpreted your question.  🤦‍♂ Sorry about that!  

I'm not familiar with the magic command #!markdown?  Is that an nbdev thing?  Where is that coming from?

BTW If you encapsulate the command in backticks you can show it in markdown

`![](like/this)`

**Comment by hamelsmu** [comment] 2020-03-17 15:28
For example you can do this

![image](https://user-images.githubusercontent.com/1483922/76872096-2f9d3080-6829-11ea-815f-157dd6ef14d0.png)


Which results in this

![image](https://user-images.githubusercontent.com/1483922/76872105-3461e480-6829-11ea-92dd-a4f1b405e37e.png)

**Comment by hamelsmu** [comment] 2020-03-17 15:40
Yes, I see that markdown in code cells are getting changed.  I have never thought about this case before.  This is something we will have to open with nbdev.  

Just to confirm, what is the use case for the syntax `#!markdown`
