### ISSUE TITLE
[Help Wanted] Microsoft Windows - CRLF to LF errors

### ISSUE THREAD

**Issue by Herman-Wu** [fastai/fastpages#213] opened 2020-03-16 19:30 UTC
Environment :  Windows 10 WSL v2  : Ubuntu 18.04.2 LTS

Reproduce steps :  use "make convert" command to convert Word documents. 
Error Message:  converter_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"

How I fix it:
      I have to change all the paths point to "/fastpages/" to "_action_files/" so the file can be found. 
      eg. 
            docker-compose.yml  :     /fastpages/action_entrypoint.sh  -> _action_files/action_entrypoint.sh
            action_entrypoint.sh:    cp /fastpages/settings.ini .    ->  cp _action_files/settings.ini .
                                                  /fastpages/word2post.sh      ->  _action_files/word2post.sh

**Comment by hamelsmu** [comment] 2020-03-17 04:18
Did you run `make build` before `make server`?   Can you check that `make build` ran successfully?

I'm not able to reproduce this error?

**Comment by hamelsmu** [comment] 2020-03-17 12:54
Closing this because I cannot reproduce this issue.  Please post this on forums.fast.ai to see if anyone else encountering this

Happy to reopen the issue with more information

**Comment by parmarsuraj99** [comment] 2020-04-17 09:28
> 
> 
> Environment : Windows 10 WSL v2 : Ubuntu 18.04.2 LTS
> 
> Reproduce steps : use "make convert" command to convert Word documents.
> Error Message: converter_1 | standard_init_linux.go:211: exec user process caused "no such file or directory"
> 
> How I fix it:
> I have to change all the paths point to "/fastpages/" to "_action_files/" so the file can be found.
> eg.
> docker-compose.yml : /fastpages/action_entrypoint.sh -> _action_files/action_entrypoint.sh
> action_entrypoint.sh: cp /fastpages/settings.ini . -> cp _action_files/settings.ini .
> /fastpages/word2post.sh -> _action_files/word2post.sh

This worked for me

**Comment by jvanelteren** [comment] 2020-04-19 18:17
Having the same problem om windows 10 home, where I installed docker toolbox. 
I did run make build. When opening the browser I get a ERR_CONNECTION_REFUSED.

`Attaching to blog_fastpages_1, blog_converter_1, blog_watcher_1, blog_jekyll_1
fastpages_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
converter_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
blog_fastpages_1 exited with code 1
blog_converter_1 exited with code 1
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating...
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |        Jekyll Feed: Generating feed for posts
jekyll_1     |                     done in 4.633 seconds.
jekyll_1     |  Auto-regeneration: enabled for '/data'
jekyll_1     |     Server address: http://0.0.0.0:4000/blog/`

**Comment by hamelsmu** [comment] 2020-04-19 19:40
Can you try running these commands ?

sed -i 's/\r//g' /fastpages/action_entrypoint.sh
sed -i 's/\r//g' /fastpages/word2post.sh

Let me know if that works if it does I think I might know how to fix

**Comment by jvanelteren** [comment] 2020-04-19 20:55
No didn't work. I'm a docker noob, but this is what I did:

I use windows so first downloaded: https://github.com/mbuilov/sed-windows/blob/master/sed-4.8-x64.exe
Then your commands did not work, had to use double quotes and remove the first '/' before _action_files. So:
sed -i "s/\r//g" _action_files/action_entrypoint.sh
sed -i "s/\r//g" _action_files/word2post.sh

Then ran "C:\Program Files (x86)\GnuWin32\bin\make.exe" server
(make was also not installed standard on my machine)

`Stopping blog_jekyll_1 ... done
Removing blog_jekyll_1    ... done
Removing blog_fastpages_1 ... done
Removing blog_watcher_1   ... done
Removing blog_converter_1 ... done
Removing network blog_default
docker-compose up
Creating network "blog_default" with the default driver
Creating blog_fastpages_1 ... done
Creating blog_converter_1 ... done
Creating blog_jekyll_1    ... done
Creating blog_watcher_1   ... done
Attaching to blog_fastpages_1, blog_converter_1, blog_watcher_1, blog_jekyll_1
fastpages_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
converter_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
blog_fastpages_1 exited with code 1
blog_converter_1 exited with code 1
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating... 
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |        Jekyll Feed: Generating feed for posts
jekyll_1     |                     done in 3.894 seconds.
jekyll_1     |  Auto-regeneration: enabled for '/data'
jekyll_1     |     Server address: http://0.0.0.0:4000/blog/`

**Comment by ScottBrenner** [comment] 2020-04-28 03:49
Confirming
```
sed -i "s/\r//g" _action_files/action_entrypoint.sh
sed -i "s/\r//g" _action_files/word2post.sh
```
Fixes this for me, thank you!

**Comment by hamelsmu** [comment] 2020-04-28 16:10
Does anyone know how to fix this issue permanently for windows users?  

Any help on this is greatly appreciated!

**Comment by hamelsmu** [comment] 2020-04-28 16:12
@noklam I believe you also encountered this issue in https://github.com/fastai/fastpages/pull/145

**Comment by hamelsmu** [comment] 2020-04-28 16:27
I'm going to close this issue and open a new one that summarizes these problems in a bit clearer way.

**Closed by hamelsmu** 2020-04-28 16:27 UTC
Labels: bug, help wanted
