### ISSUE TITLE
Fail to run local server from Debian

### ISSUE THREAD

**Issue by tiega** [fastai/fastpages#351] opened 2020-07-08 17:02 UTC
## Required information

1. Steps to reproduce the problem

Run from a repo in Debian Testing

```bash
make server
```

Note: the same command works on MacOS

2. A link to the notebook or markdown file where the error is occurring

https://github.com/tiega/fastblog

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

```
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating...
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |        Jekyll Feed: Generating feed for posts
jekyll_1     |   Liquid Exception: Connection reset by peer - SSL_connect in /data/_posts/2020-01-14-test-markdown-post.md
jekyll_1     | /usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
jekyll_1     |  from /usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
jekyll_1     |  from /usr/local/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
jekyll_1     |  from /usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
jekyll_1     |  from /usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
jekyll_1     |  from /usr/local/lib/ruby/2.7.0/net/http.rb:606:in `start'
jekyll_1     |  from /usr/gem/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:73:in `fetch'
jekyll_1     |  from /usr/gem/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:209:in `live_response'
jekyll_1     |  from /usr/gem/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:180:in `render'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
jekyll_1     |  from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:80:in `render_document'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
jekyll_1     |  from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
jekyll_1     |  from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
jekyll_1     |  from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
jekyll_1     |  from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
jekyll_1     |  from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
jekyll_1     |  from /usr/gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
jekyll_1     |  from /usr/local/bundle/bin/jekyll:29:in `load'
jekyll_1     |  from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

The same error `Liquid Exception: Connection reset by peer - SSL_connect in /srv/jekyll/_posts/2020-01-14-test-markdown-post.md` is emitted when I run `make build`. I followed all the steps in the troubleshooting guide, and all docker builds come back to the same error. I've never used Ruby before so I do not know how to debug this problem. 

I don't think there's anything wrong with my repo as the blog builds just fine on MacOS. The blog also builds fine on github as seem at https://tiega.github.io/fastblog.

**Comment by hamelsmu** [comment] 2020-07-10 17:51
Looks like an error with Docker and networking being blocked.  Is this something you have tried to troubleshoot?

**Comment by adityassrana** [comment] 2020-07-11 08:46
Check if running with sudo solves your problem. It did for me

````
sudo make server
````

**Comment by tiega** [comment] 2020-07-14 12:54
Previously I wasn't in the `docker` group and I had to use `sudo` anyways. I've now added my user to the `docker` group and the problem persists. I've confirmed this bug in two different installs of Debian, where docker and docker-compose work fine otherwise. Any ideas on how to troubleshoot the network problem?

**Comment by hamelsmu** [comment] 2020-07-16 04:47
No idea as no experience with this and not sure how to reproduce this error

**Comment by hamelsmu** [comment] 2020-07-25 20:49
Closing this issue as I cannot reproduce this error.

**Closed by hamelsmu** 2020-07-25 20:49 UTC
Labels: bug

**Comment by hamelsmu** [comment] 2020-07-31 01:46
@tiega I fixed this issue in https://github.com/fastai/fastpages/pull/372

You can upgrade to get the fix or apply the same changes to your repo
