### ISSUE TITLE
Math on notebook not rendering

### ISSUE THREAD

**Issue by gjunqueira-sys** [fastai/fastpages#600] opened 2021-12-28 15:13 UTC
## Required information

1. Steps to reproduce the problem
* Just execute notebook. Output is not rendering. So I hid output and tried to copy and past latex code on markdown cell. This also didnt work.

2. A link to the notebook or markdown file where the error is occurring
https://gjunqueira-sys.github.io/J-J-Engineering-Blog/jupyter/math/calculus/symbolics/julialang/2021/12/28/EulersMethod.html

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
no errors are happening.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).
![screenshot](https://user-images.githubusercontent.com/54514899/147580236-836f1aec-6ba7-4d02-81f5-69ba64857148.png)

**Comment by hamelsmu** [comment] 2022-01-06 22:48
duplicate of https://github.com/fastai/fastpages/issues/577, will try to fix this son

**Closed by hamelsmu** 2022-01-06 22:48 UTC
Labels: bug
