### ISSUE TITLE
[02.03.2020]: [Failing Jekyll build with dash line in text cell]

### ISSUE THREAD

**Issue by uwesterr** [fastai/fastpages#162] opened 2020-03-02 11:03 UTC
when adding the dash line in a text cell like below
`
#### Get myconfig.py
> Note: In `myconfig.py` therer are parameters which control the training such as: 
 
 ---
 
 line parameter --type to the python manage.py train and drive commands.

`
i get the following error mail

> Run failed for master (13090ea)

Repository: uwesterr/MlFastAiBlog
Workflow: CI
Duration: 2 minutes and 38.0 seconds
Finished: 2020-03-02 10:42:14 UTC

View results

Jobs:
https://github.com/uwesterr/MlFastAiBlog/runs/479332637 failed (0 annotations)

once i deleted the dash line like so
`
#### Get myconfig.py
> Note: In `myconfig.py` therer are parameters which control the training such as: 
 
 line parameter --type to the python manage.py train and drive commands.

`
the build goes through with no problems

**Comment by hamelsmu** [comment] 2020-03-02 15:19
Please provide a link to the notebook causing the problem thank you

**Comment by uwesterr** [comment] 2020-03-02 15:24
I deleted the "---" in the text section so the problem is not in any file anymore

**Comment by hamelsmu** [comment] 2020-03-02 15:28
Closing issue due to no example provided.

**Closed by hamelsmu** 2020-03-02 15:28 UTC
Labels: bug

**Comment by hamelsmu** [comment] 2020-03-02 15:45
@uwesterr  Please reopen the issue if example is available, as it is possible I am misreading your comment above, I was not able to reproduce.

**Comment by uwesterr** [comment] 2020-03-03 09:14
cannot reproduce it either, will send example when i can

**Comment by uwesterr** [comment] 2020-03-05 20:10
now i could reproduce it, had to zip the file because .ipynb is not supported by GitHub
[2020-03-01-TrainDonkeyCar.ipynb.zip](https://github.com/fastai/fastpages/files/4294955/2020-03-01-TrainDonkeyCar.ipynb.zip)
