### ISSUE TITLE
[3-30-2020]: [1st PR fail when user name is all number]

### ISSUE THREAD

**Issue by 903124** [fastai/fastpages#236] opened 2020-03-29 16:44 UTC
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

Error on modifying file 
![image](https://user-images.githubusercontent.com/13618001/77854908-9ce49480-721f-11ea-8a1f-840e60c38175.png)

**Comment by hamelsmu** [comment] 2020-03-29 17:44
I was not able to reproduce this error.  No link to the repo was given so no troubleshooting steps could be undertaken.  Closing this issue.

https://github.com/hamelsmu/test-fast-pages/pull/1

**Comment by 903124** [comment] 2020-03-30 03:06
Thanks for the reply here is the failed initial commit 

https://github.com/903124/fastpage_test/runs/544271197

**Comment by 903124** [comment] 2020-03-31 03:49
The PR fail due to regex of github user name and since my username is in all number it would fail

**Comment by hamelsmu** [comment] 2020-03-31 04:56
Yes.  reopening this issue.  will fix it

**Closed** 2020-03-31 05:02 UTC
Labels: bug

**Comment by 903124** [comment] 2020-03-31 05:06
Work fine now. Thanks!
