### ISSUE TITLE
[20200322]: [Image Caption does not work]

### ISSUE THREAD

**Issue by noklam** [fastai/fastpages#225] opened 2020-03-22 08:04 UTC
Image caption with file name does not work.

The one with URL can convert successfully, but if it is a local path it will not convert successfully

![image](https://user-images.githubusercontent.com/18221871/77245015-47741a80-6c56-11ea-8ea5-478477ebfb28.png)

# Reproduce
https://github.com/fastai/fastpages/blob/master/_notebooks/2020-02-20-test.ipynb
Just try to add a caption as shown above.

# Error 
![image](https://user-images.githubusercontent.com/18221871/77245078-d1bc7e80-6c56-11ea-9121-60c9500d2ef9.png)

**Comment by hamelsmu** [comment] 2020-03-22 14:45
Can you please file an issue in nbdev about this?  The repo is  fastai/nbdev

According to the error message you do not have an image file relative to your notebook.  But I see this is in your repo so not exactly sure what is happening. 

Can you open a terminal window in the running container and verify that the file exists?  Instructions on how to do this is in the development guide

**Comment by hamelsmu** [comment] 2020-03-22 14:49
Oh wait you linked to fastpages not your own repo I bet you just don’t have this icon locally !  In fact that’s exactly what the error says.  I’m closing because I cannot reproduce if still having this error please open on nbdev but check your local files first

**Comment by noklam** [comment] 2020-03-22 15:05
Sorry I should have make it clearer.  The error is throw by the docker.  The image is there as long as I remove the caption part.

I tried look into nbdev but I couldn't figure it out.  My guess is the regex part fail to extract the file name correctly,  it think the caption is part of the filename.

However,  if it is not a local file but URL, the caption works

**Comment by hamelsmu** [comment] 2020-03-22 15:20
Ok I’ll take another look

**Comment by hamelsmu** [comment] 2020-03-22 17:16
@noklam it appears that the caption, in this case, is treated like part of the file name.  Can you do me a favor and open an issue in nbdev?  Thank you!  I'll go ahead and close this.

**Closed by hamelsmu** 2020-03-22 17:16 UTC
Labels: bug

**Comment by hamelsmu** [comment] 2020-03-22 17:35
@noklam one more thing, in the meantime you can have captions like this by making this into a markdown cell.  This is what they are doing in nbdev

```html
<img alt="Exporting from nbdev" width="700" caption="An example of a function defined in one cell (marked with the export flag) and explained, along with a visual example, in the following cells" src="my_icons/fastai_logo.png" />
```

Please let me know if this works for you

**Comment by noklam** [comment] 2020-03-22 18:34
Thank you, appreciate the quick response as always!

**Comment by ducha-aiki** [comment] 2020-03-25 19:37
Hi,

Could you please tell me, how could I update nbdev used by fastpages (https://github.com/fastai/nbdev/issues/111 related). I have installed the recent version, but it seems that fastpages uses some other one

**Comment by hamelsmu** [comment] 2020-03-25 19:45
We cannot yet.  We have to wait until they cut a new release, and then I need to cut a new release of fastpages.  [nbdev](https://pypi.org/project/nbdev/#history) is on 0.2.15, when they bump I should be able to rebuild.  

Sorry about the lag, this is kind of necessary to provide stability over time.  

@sgugger - mind cutting a release?

**Comment by sgugger** [comment] 2020-03-25 19:46
Sure thing.

**Comment by ducha-aiki** [comment] 2020-03-25 19:59
Wow, thanks! 

@hamelsmu I understand about stability. I was thinking more about local build, like editing `_action_files/fastpages-nbdev.Dockerfile` and building it again, which I am figuring out how to do now.

**Comment by ducha-aiki** [comment] 2020-03-25 20:02
I have added `	docker build -t hamelsmu/fastpages-nbdev -f _action_files/fastpages-nbdev.Dockerfile .` to Makefile, `build` section.
And `RUN pip install git+https://github.com/fastai/nbdev` to `_action_files/fastpages-nbdev.Dockerfile'`.

It seems to be working locally. Would work online as well or not?

**Comment by hamelsmu** [comment] 2020-03-25 21:37
@ducha-aiki fastpages is now updated with the latest version of nbdev and all Docker containers have been rebuilt. 

Cheers

P.S.  We cannot do this dev build online as we freeze the environment for stability reasons for everyone.  The automation in GitHub actions pulls from this frozen environment which allows a ~ 1 < 2 minute build speed.   If you build from scratch this will increase the build time to ~ 20 minutes.  
That would be a poor experience for most users

**Comment by ducha-aiki** [comment] 2020-03-25 21:42
@hamelsmu 
Thanks again and a lot!

I am quite a newbie for GitHub Actions. Am I right that given enough expertize (say, day of experiments and googling) I could change then to use my own environment (whatever slow it could be) and not the common one? I am thinking about the integration of https://github.com/jfbercher/jupyter_latex_envs into fastpages for my PhD thesis.

**Comment by hamelsmu** [comment] 2020-03-25 22:31
I have no idea, but in theory it’s possible to change whatever you want

**Comment by noklam** [comment] 2020-04-10 15:30
@ducha-aiki  Are you able to do image caption in notebook? I still getting the same error, I just upgraded fastpages today

> jekyll_1     |
> watcher_1    | [Errno 2] No such file or directory: '/data/_notebooks/nb_img/ppt_high_res_02.png "Notice the sharpness of the text"'    
> watcher_1    | Traceback (most recent call last):

**Comment by noklam** [comment] 2020-04-10 15:31
For the record, attachment:image.png seems also broken.

**Comment by hamelsmu** [comment] 2020-04-10 17:22
@noklam can you file a new issue with a reproducible example of what is broken?  Thanks

**Comment by ducha-aiki** [comment] 2020-04-10 17:28
@noklam I have no problems. But the result would NOT be in notebook itself (at least, I don't see captions there), instead it would be in HTML-file generated with it.
See here:
screenshot from notebook
https://github.com/ducha-aiki/wide-baseline-stereo-blog/blob/master/_notebooks/2020-03-27-intro.ipynb
![image](https://user-images.githubusercontent.com/4803565/79010028-4cdfc900-7b61-11ea-94d3-c68d6e181ca2.png)

screenshot from generated html:
https://ducha-aiki.github.io/wide-baseline-stereo-blog/2020/03/27/intro.html
![image](https://user-images.githubusercontent.com/4803565/79010052-5ec16c00-7b61-11ea-8d6d-97147336c242.png)

**Comment by noklam** [comment] 2020-04-10 17:37
> @noklam I have no problems. But the result would NOT be in notebook itself (at least, I don't see captions there), instead it would be in HTML-file generated with it.
> See here:
> screenshot from notebook
> https://github.com/ducha-aiki/wide-baseline-stereo-blog/blob/master/_notebooks/2020-03-27-intro.ipynb
> ![image](https://user-images.githubusercontent.com/4803565/79010028-4cdfc900-7b61-11ea-94d3-c68d6e181ca2.png)
> 
> screenshot from generated html:
> https://ducha-aiki.github.io/wide-baseline-stereo-blog/2020/03/27/intro.html
> ![image](https://user-images.githubusercontent.com/4803565/79010052-5ec16c00-7b61-11ea-8d6d-97147336c242.png)


> watcher_1    | converting: _notebooks/2020-04-11-test-attachment.ipynb
> watcher_1    | [Errno 2] No such file or directory: '/data/_notebooks/nb_img/ppt_high_res_02.png \\"123\\"'

Weird, I just upgraded fastpages and I am still getting this error, which is due to nbdev parsing the caption as filename. That bug should have been fixed already.

@ducha-aiki  Can you kindly help testing attachment:image.png works? (You need to open a notebook and convert it to a markdown cell first, and then you can just copy and paste a screenshot to it directly by Ctrl-C, Ctrl-V)

**Comment by noklam** [comment] 2020-04-10 18:19
https://github.com/fastai/fastpages/issues/248
@hamelsmu I have created an issue for the attachment:image.png issue.

For the image caption, the problem seems to be local environment. As it fails to convert in my local machine but when I push to Github the page build is fine. I will update if I find any issue.

So far I have try `make build` `make server` already, no luck yet.
