### ISSUE TITLE
Delay first build upon checking out repo template

### ISSUE THREAD

**Issue by FReeshabh** [fastai/fastpages#39] opened 2020-02-14 04:40 UTC
The tag twitter on line 73 in _posts/2020-01-14-welcome.md is not a recognized Liquid tag.

Getting this error, getting other errors after removing line 73, mostly twitter not working

**Comment by hamelsmu** [comment] 2020-02-14 15:37
@FReeshabh  are you using the most up to date version of this repo?  I no longer have a post called `2020-01-14-welcome.md`.  This repo is being developed rapidly so it could be this was previously addressed or fixed.  

The [current version in master](https://fastai.github.io/fastpages/2020/01/14/test-markdown-post.html) is rendering tweetcards correctly.  I'll close this for now, please reopen if you are able to reproduce this from the current version . 

🙇  thank you!

**Comment by hamelsmu** [comment] 2020-02-14 15:38
_P.S._ Cool Blog, https://freeshabh.github.io/ BTW!  If you do manage to use this template successfully especially with Jupyter please let me know!

**Comment by hamelsmu** [comment] 2020-02-14 17:37
@FReeshabh I just realized you are using `fast_template` for your blog.  Please keep in mind that [fastpages](https://github.com/fastai/fastpages) is a separate project and features here may not work with fast_template.  I suggest you fork this repo for your blog instead if you want these additional features.

**Comment by FReeshabh** [comment] 2020-02-14 22:40
@hamelsmu I switched back by to fast template. I'm gonna try to use fastapges, maybe I didn't do it correctly earlier. I'll update back

**Comment by drscotthawley** [comment] 2020-02-17 05:45
I realize this is closed, but I get essentially the same error with a fresh checkout of the latest version of the fastpages repo, so thought I'd post here:

"Your site is having problems building: The tag twitter on line 73 in _posts/2020-01-14-test-markdown-post.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error."

I can open a new Issue if you prefer. 

My cloned fastpages repo is https://github.com/drscotthawley/devblog2

**Comment by hamelsmu** [comment] 2020-02-17 07:13
Hi @drscotthawley this is your error: https://github.com/drscotthawley/devblog2/runs/449901792?check_suite_focus=true#step:5:901

Something about an embedded picture that is causing problems in your notebook conversion.  I’ll take a look at this sometime next week.

**Comment by drscotthawley** [comment] 2020-02-17 07:17
Oh wow, we were working at the exact same time tonight!   The error you mentioned just now is after installing some new posts -- I *just* opened an issue on that seconds ago! 

But when I wrote on this issue above, it was a brand-new check-out of the repository, with no other posts but the original one (which was giving the twitter error.)

**Comment by hamelsmu** [comment] 2020-02-17 07:21
Oh in that case, I believe your first error is user error: https://github.com/drscotthawley/devblog2/runs/449804933?check_suite_focus=true#step:8:13

You forgot to set the deploy key?  If so please close this issue

**Comment by hamelsmu** [comment] 2020-02-17 07:27
I know why this happens, it is because when you first check out the template, GitHub makes an initial commit to master, this triggers the entire workflow right away, before you have a chance to set anything up.  You get an error initially, but then after you fix everything the error goes away.  

I should re-arrange the order of the setup steps so this goes away.  I’m working on a solution right now that will automate all the setup steps and this problem will then go away, hopefully.  

We should leave this issue open

**Comment by drscotthawley** [comment] 2020-02-17 07:31
Ah, ok!  Thanks.  I have re-added your original markdown post, and confirmed that it builds correctly with the original twitter tag as you have it. 

(I temporarily removed the notebook file that was causing other problems.)

**Comment by hamelsmu** [comment] 2020-02-17 08:29
I changed the ordering of the setup instructions if anyone wants to go ahead and give it a shot.  The new ordering of steps should avoid confusing error messages.

**Comment by DataLovecraft** [comment] 2020-02-18 17:53
I'm still getting this error:
[1_see-page-build-payload.txt](https://github.com/fastai/fastpages/files/4220794/1_see-page-build-payload.txt)

my cloned repo: https://github.com/DataLovecraft/DataLovecraft.github.io

For step 1, in deploying your ssh, 'Make sure you select Allow write access when adding this key to your GitHub account.'

Do I need a specific name? or can I name it anything, and this is where the public key goes?

**Comment by hamelsmu** [comment] 2020-02-18 22:55
https://github.com/fastai/fastpages/pull/69 will close this PR, we are rebuilding the setup process to make it easier to follow.

**Closed** 2020-02-18 23:35 UTC
Labels: bug, documentation, in-progress
